baseURL = "https://protux.de/"
languageCode = "en-gb"
title = "protux.de - Random thoughts and stuff"

theme = "notepadium"
enableRobotsTXT = true
dateFormat = "02.01.2006"
license = "CC-BY SA"

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/
